<?php
/**
 * DRAFT - NOT TO BE COMMITTED
 *
 * Target path (upstream e107inc/e107 master):
 *   e107_core/override/url/news/sef_url.php
 *
 * Overrides the core profile e107_core/url/news/sef_url.php
 * ("Friendly URLs with ID"), reshaping every rule from
 *   /news/view/{id}/{slug}   to   /news/view-{id}-{slug}
 * so that URLs produced by e107-2.4.x-Lite's eplugins/news/e_url.php keep
 * working natively - parsed AND generated by upstream, with no redirects.
 *
 * Stored pref value once selected in admin -> URL configuration:
 *   url_config['news'] = 'override/sef'
 * Resolved class name: override_news_sef_url  (location_module_custom_url)
 *
 * PHP 7.4 safe.
 */
if (!defined('e107_INIT')) { exit; }

class override_news_sef_url extends eUrlConfig
{
	public function config()
	{
		return array(
			'config' => array(
				'allowMain'     => true,                    // news may be set as site root namespace
				'legacy'        => '{e_BASE}news.php',      // legacy entry point (news has no controller)
				'format'        => 'path',                  // use the rule set below
				'defaultRoute'  => 'list/items',            // declared for parity; not consumed by current core
				'urlSuffix'     => '',
				'allowVars'     => false,                   // only route vars + per-rule allowVars survive
				'matchValue'    => 'empty',                 // a rule with an empty value is skipped when creating
				'mapVars'       => array(
					'news_id'  => 'id',
					'news_sef' => 'name',
				),
			),

			// Order matters: first match wins, both when parsing and when creating.
			'rules' => array(

				// ---- index / default list : /news ----
				''                                          => array('list/items',
					'allowVars'   => array('page'),
					'legacyQuery' => 'default.0.{page}',
				),
				'Category'                                  => array('list/items',
					'allowVars'   => array('page'),
					'legacyQuery' => 'default.0.{page}',
				),

				// ---- all news : /news/all ----
				'all'                                       => array('list/all',
					'allowVars'   => array('page'),
					'legacyQuery' => 'all.0.{page}',
				),

				// ---- item : /news/view-{id}-{slug} ----
				'view-<id:{number}>-<name:{sefsecure}>'     => array('view/item',
					'allowVars'   => array('page'),
					'mapVars'     => array('news_id' => 'id', 'news_sef' => 'name'),
					'legacyQuery' => 'extend.{id}',
				),
				// fallback when news_sef is empty : /news/view-{id}
				'view-<id:{number}>'                        => array('view/item',
					'allowVars'   => array('page'),
					'mapVars'     => array('news_id' => 'id'),
					'legacyQuery' => 'extend.{id}',
				),

				// ---- category list : /news/category-{id}-{slug} ----
				'category-<id:{number}>-<name:{sefsecure}>' => array('list/category',
					'allowVars'   => array('page'),
					'mapVars'     => array('category_id' => 'id', 'category_sef' => 'name'),
					'legacyQuery' => 'list.{id}.{page}',
				),
				'category-<id:{number}>'                    => array('list/category',
					'allowVars'   => array('page'),
					'mapVars'     => array('category_id' => 'id'),
					'legacyQuery' => 'list.{id}.{page}',
				),

				// ---- category brief : /news/short-{id}-{slug} ----
				'short-<id:{number}>-<name:{sefsecure}>'    => array('list/short',
					'allowVars'   => array('page'),
					'mapVars'     => array('category_id' => 'id', 'category_sef' => 'name'),
					'legacyQuery' => 'cat.{id}.{page}',
				),
				'short-<id:{number}>'                       => array('list/short',
					'allowVars'   => array('page'),
					'mapVars'     => array('category_id' => 'id'),
					'legacyQuery' => 'cat.{id}.{page}',
				),

				// ---- archives : /news/day-{yyyymmdd}, /news/month-{yyyymm} ----
				'day-<id:{number}>'                         => array('list/day',
					'allowVars'   => array('page'),
					'legacyQuery' => 'day.{id}.{page}',
				),
				'month-<id:{number}>'                       => array('list/month',
					'allowVars'   => array('page'),
					'legacyQuery' => 'month.{id}.{page}',
				),

				// ---- tag / author : /news/tag-{tag}, /news/author-{author} ----
				'tag-<tag:{secure}>'                        => array('list/tag',
					'allowVars'   => array('page'),
					'legacyQuery' => 'tag={tag}&page={page}',
				),
				'author-<author:{secure}>'                  => array('list/author',
					'allowVars'   => array('page'),
					'mapVars'     => array('user_name' => 'author'),
					'legacyQuery' => 'author={author}&page={page}',
				),

				/*
				 * OPTIONAL - upstream-shaped URLs kept alive for parsing only.
				 * They are declared LAST, so createUrl() never selects them and every
				 * emitted link stays hyphen-shaped; inbound /news/view/146/slug still
				 * resolves instead of 404ing. Leave commented out unless you actually
				 * need it: two URL shapes for one item is duplicate content, mitigated
				 * (not removed) by the canonical tag news.php already emits.
				 *
				'view/<id:{number}>/<category:{sefsecure}>/<name:{sefsecure}>' => array('view/item',
					'allowVars'   => array('page'),
					'mapVars'     => array('news_id' => 'id', 'category_sef' => 'category', 'news_sef' => 'name'),
					'legacyQuery' => 'extend.{id}',
				),
				'view/<id:{number}>/<name:{sefsecure}>' => array('view/item',
					'allowVars'   => array('page'),
					'mapVars'     => array('news_id' => 'id', 'news_sef' => 'name'),
					'legacyQuery' => 'extend.{id}',
				),
				'view/<id:{number}>' => array('view/item',
					'allowVars'   => array('page'),
					'mapVars'     => array('news_id' => 'id'),
					'legacyQuery' => 'extend.{id}',
				),
				'Category/<id:{number}>/<name:{sefsecure}>' => array('list/category',
					'allowVars'   => array('page'),
					'mapVars'     => array('category_id' => 'id', 'category_sef' => 'name'),
					'legacyQuery' => 'list.{id}.{page}',
				),
				'Short/<id:{number}>/<name:{sefsecure}>' => array('list/short',
					'allowVars'   => array('page'),
					'mapVars'     => array('category_id' => 'id', 'category_sef' => 'name'),
					'legacyQuery' => 'cat.{id}.{page}',
				),
				'Day/<id:{number}>'   => array('list/day',   'allowVars' => array('page'), 'legacyQuery' => 'day.{id}.{page}'),
				'Month/<id:{number}>' => array('list/month', 'allowVars' => array('page'), 'legacyQuery' => 'month.{id}.{page}'),
				'Tag/<tag:{secure}>'  => array('list/tag',   'allowVars' => array('page'), 'legacyQuery' => 'tag={tag}&page={page}'),
				'Author/<author:{secure}>' => array('list/author', 'allowVars' => array('page'), 'legacyQuery' => 'author={author}&page={page}'),
				 */
			),
		);
	}

	/**
	 * Admin callback - drives the label, description and examples shown in
	 * admin -> URL configuration, and the "Rebuild" SEF generator button.
	 * lan_eurl.php is loaded by that page; the defined() guards keep the file
	 * safe if admin() is ever called outside it.
	 */
	public function admin()
	{
		static $admin = null;

		if ($admin === null)
		{
			$admin = array(
				'labels' => array(
					'name'        => defined('LAN_EURL_CORE_NEWS') ? LAN_EURL_CORE_NEWS : 'News',
					'label'       => 'Friendly URLs with ID, hyphenated (Lite-compatible)',
					'description' => 'Legacy e107-2.4.x-Lite URL shape: /news/view-{id}-{slug}. Keeps indexed Lite URLs working natively, without redirects.',
					'examples'    => array(
						'{SITEURL}news/view-1-news-title',
						'{SITEURL}news/category-1-news-category',
					),
				),
				'generate'  => array('table' => 'news', 'primary' => 'news_id', 'input' => 'news_title', 'output' => 'news_sef'),
				'form'      => array(),
				'callbacks' => array(),
			);
		}

		return $admin;
	}
}